### ISSUE TITLE
Add guidance on registration of claims corresponding to YANG objects

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#10]
See https://mailarchive.ietf.org/arch/msg/rats/jBCYPK2hly554HGYTXZXa2t_AGw.

Future claims could be added that correspond directly to YANG objects (https://tools.ietf.org/html/rfc6020).  There should be guidance in the document as to how such objects can be reflected in the CWT claims registry.

For CBOR claims, this could be as simple as providing a reference to https://datatracker.ietf.org/doc/draft-ietf-core-yang-cbor/.  It should be confirmed whether https://tools.ietf.org/html/rfc7951 is sufficient to address future JWT claims.

**Comment by nedmsmith** [comment]
Possibly it doesn't make sense to provide guidance unless it is thought to be needed by draft-birkholz-rats-basic-yang-module-01  and/or draft-fedorkow-rats-network-device-attestation-00 or if there is a use case that provides context for understanding how EAT tokens are used in the context of YANG encodings. Possibly, the information models in both EAT and YANG define claims that are semantically the same/similar. But the WG seems to be in favor of allowing this or at least relying on readers of the drafts to spot semantic differences. Even so, if no use case requires use of EAT (CBOR/JSON) and YANG encodings then possibly there is no compelling need to define this now.

**Comment by gmandyam** [comment]
@nedmsmith 

I assume that there will be YANG claims that correspond to TPM information fields (as there already are in draft-birkholz-rats-basic-yang-module).  Having the guidance on how to add YANG claims to an EAT token (without actually specifying those claims) could allow developers to basically pick and choose which TPM information fields they would like if they wanted to enrich an EAT token, as opposed to sending an entire TPM attestation along with the EAT.

**Comment by nedmsmith** [comment]
﻿
﻿The challenge is who signs the EAT token if legacy TPM doesn’t know how to sign an EAT. Does it still make sense to say the same thing in an EAT if it is also said in the TPM Evidence?

Sent from my iPhone

On Oct 17, 2019, at 6:58 PM, gmandyam <notifications@github.com> wrote:

﻿

@nedmsmith<https://github.com/nedmsmith>

I assume that there will be YANG claims that correspond to TPM information fields (as there already are in draft-birkholz-rats-basic-yang-module). Having the guidance on how to add YANG claims to an EAT token (without actually specifying those claims) could allow developers to basically pick and choose which TPM information fields they would like if they wanted to enrich an EAT token, as opposed to sending an entire TPM attestation along with the EAT.

**Comment by gmandyam** [comment]
>﻿The challenge is who signs the EAT token if legacy TPM doesn’t know how to sign an EAT. Does it still make sense to say the same thing in an EAT if it is also said in the TPM Evidence?

If one was to attempt such an operation, then I think it would look a lot like the  signing operation described in the webauthn specification - see https://www.w3.org/TR/webauthn/#tpm-attestation.  In that case, a digest is created of the data to be signed and the digest is presented to the TPM in the TPMS_ATTEST.extraData field.  So any RP that would try to verify the EAT token would have to know what digest to expect.    If there is any information contained in the EAT token that is dynamic in nature (e.g. location in a mobile device), then I don't know how that would work.

That is why I think that if an implementation requires information equivalence between the TPM attestation and EAT, it is preferable to add the desired TPM information fields to the EAT (e.g. via a YANG claim) rather than the other way.

**Comment by nedmsmith** [comment]
The architectural question relates to what environment is the “Attesting env” and whether or not that environment is able to support an IETF RATS format (CBOR, JSON, YANG). The TPM versions support binary and in TPM2 an optional X.509 (BER) format. If the expectation of RATS is that an EAT token is needed that encapsulates the TPM attested evidence, then one should ask whether the thing creating the EAT is an “Attesting” environment. If it is, but isn’t a TPM then the use cases (or some other specification) should inform as to whether that makes sense. Having a spec that says “something that might not be an attesting env should create an EAT except for the fact that the spec mandates it” doesn’t seem right.

If the idea is to use the TPMS_ATTEST.extraData field to cause the TPM (aka attesting env) to sign the EAT. However the TPM may refuse to sign with an attestation key because these keys refuse to sign data that is opaque (to the attesting env). Even so, it would be

The correct use of TPMS_ATTEST.extraData would be as a nonce to show freshness of the attestation event. This could be an EAT.nonce value. I’m having difficulty understanding the use case where the EAT contains an encapsulation of the TPM signed Evidence.

-Ned

On 10/22/19, 10:39 AM, "gmandyam" <notifications@github.com<mailto:notifications@github.com>> wrote:


The challenge is who signs the EAT token if legacy TPM doesn’t know how to sign an EAT. Does it still make sense to say the same thing in an EAT if it is also said in the TPM Evidence?

If one was to attempt such an operation, then I think it would look a lot like the signing operation described in the webauthn specification - see https://www.w3.org/TR/webauthn/#tpm-attestation. In that case, a digest is created of the data to be signed and the digest is presented to the TPM in the TPMS_ATTEST.extraData field. So any RP that would try to verify the EAT token would have to know what digest to expect. If there is any information contained in the EAT token that is dynamic in nature (e.g. location in a mobile device), then I don't know how that would work.

That is why I think that if an implementation requires information equivalence between the TPM attestation and EAT, it is preferable to add the desired TPM information fields to the EAT (e.g. via a YANG claim) rather than the other way.

**Comment by laurencelundblade** [comment]
The TPM discussion aside, it seems this is about how to relate definitions of YANG objects to claims in CBOR or JSON and vice versa.

Looks to me YANG objects are defined in YANG modules and that there are a LOT of them. There's no registry. It looks like a real chore to reconcile all the YANG objects with CWT/JWT claims. Does that sound right?

A use case here might be one were the Verifier receives some attestation evidence in YANG format and needs to produce attestation results in EAT format. Having the same claims or similar claims in both would make that work much better.

Is there a YANG module for attestation? We could limit ourselves to that and some reconciliation might be doable.

**Comment by laurencelundblade** [comment]
Closed per discussion at virtual interim December 12, 2023
