### ISSUE TITLE
svn claim

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/eat#111]
https://cwe.mitre.org/data/definitions/1328.html provides context for svn (security version number). There are many systems that use it. It would be helpful if EAT could include a claim for svn.

Something like:

svn-type = int
svn-claim = ( svn => svn-type)

I can help contribute text if needed.

**Comment by laurencelundblade** [comment]
If I understand, the claim would report the value of the (hopefully) immutable rollback counter that the HW is storing. This could also be thought of as the minimum firmware version. The counter / version for the firmware that is installed is reported separately from this. In most cases they will be the same. In some cases the installed firmware version may be ahead. If the installed firmware version is behind, then something very bad has happened.

So, yes, this seems like a good thing to add. Thank you.

Would be better to call it "minfw" (minimum firmware version), or "firmware rollback counter"? 

I reused the CoSWID version scheme classification for HW version numbers. See the -10 draft. It seems like that would be the thing to do here. Just clone the hw-version claim and call it "minfw"?

I expect the version of the installed firmware to be reported as part of the swevidence claim, most likely in a CoRIM/CoMID (CoSWIDs don't seem very good for firmware since they are file path oriented).

**Comment by laurencelundblade** [comment]
I don't think this blocks last call unless Ned or someone else wants this.

**Comment by gmandyam** [comment]
@nedmsmith - do you feel this is LC blocking?  If not, we can deprioritize this issue.

**Comment by laurencelundblade** [comment]
Closing because we have lots to do and there's no ground swell of support.

It doesn't seem like a bad idea, but is not critical or central to EAT. It can be added as an independent registration or a separate standard.
