### ISSUE TITLE
RAND UEID's - minimum requirements to prevent clashes from different manufacturers

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#21]
Current text (-01) does not state assumptions on rand generation that would be necessary to minimize the probability of collisions from different manufacturers.  This could be added to the Security Considerations section.

**Comment by nedmsmith** [comment]
An attacker might purposefully reuse an existing EUID (random or not). The security of attestation should not depend on a convention for whether the generation algorithm includes entropy. Even if values are guessable, there should be an understanding by the Verifier for how to detect that the value is authentic / spoofed. The entity (vendor) creating the EUID is not motivated to issue duplicates. Whether they select a method based on entropy or assigned values should be a vendor specific choice (IMO).

**Comment by laurencelundblade** [comment]
@nedmsmith Addressing your comment from July 22, 2019. The relying party has to trust the UEID based on the fact that it was signed by the attester. They trust the attester because of endorsements. There's nothing more that can be done.

The vendor can choose the type they want, random, MAC address.... They can even switch from one day to the next.

**Comment by laurencelundblade** [comment]
I believe this is fixed with #35
