### ISSUE TITLE
can SUEID and UEID be identical?

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#291]
> Can the SUEID be *identical* to the UEID?  Or, MUST it be different for
    > privacy reasons?

Also not dealt with.

    > How are labels for the SUEID assigned? ("FDO")?

Not addressed.

**Comment by laurencelundblade** [comment]
Yes, SUEID and UEID can have the same value, but if SUEID is changed, UEID can't change, because the rule for UEID is that it can't change. I think the rules are clear and we don't need to state this explicitly but am open to adding some text to explain it.

EAT has no privacy rules. Just privacy considerations. Section 8.1 gives coverage to UEID and SUEID.


The text explains reasonably well that assignment of SUEID labels is outside the scope of this document. (PR #328 does change "FDO" to "XYZ" because "FDO" doesn't actually exist in FIDO on-boarding, but you comment was not about that).

**Comment by dthaler** [comment]
A profile could add constraints between UEID and SUEID if needed, but the base EAT has no restrictions about whether they can or cannot match.  My believe is that the draft is fine and this issue is a sufficient record of the discussion.  This was discussed in today's interim meeting.

**Comment by laurencelundblade** [comment]
Closed per discussion at virtual interim December 12, 2023
