### ISSUE TITLE
what is purpose of tolerating jti/cti claims

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#294]
> 13) 4.3.1. Token ID Claim (cti and jti) Should it even be present?

A sentence was removed, but it still seems to me that cti and jti MUST be
ignored if present, and SHOULD not be sent.

**Comment by gmandyam** [comment]
There are several instances where an attestation is required but a nonce is not possible due to transport limitations (e.g. one-way communication such as BLE-AD).  A freshness mechanism supported by the token issuer is better than nothing in these situations.

If the intent with this issue  is to cover the case where both a cti and nonce are sent (CWT case), then the cti cannot be ignored if it included in the payload used for generation of the signature.  It could be ignored for the purpose of freshness assessment in that case, but the text states "MUST be ignored if present" which is not the same.

**Comment by laurencelundblade** [comment]
At this point we exclude no claims from EAT for any reason. Anything in the IANA registries is fair game. Seems, we'd have to have a really good reason to explicitly, universally and categorically exclude a particular claim.

Do you have a particular problem in mind? I can't think of anything myself.

I don't think Giri's freshness example is the only use for CTI/JTI. Someone might just want a good unique ID for tracking tokens in a database that doesn't depend on anything else like time, device ID, ...

**Comment by gmandyam** [comment]
>I don't think Giri's freshness example is the only use for CTI/JTI. Someone might just want a good unique ID for tracking tokens in a database that doesn't depend on anything else like time, device ID, ...

CTA WAVE's Common Access Token, which has been presented at the IETF CDNI WG (https://datatracker.ietf.org/meeting/114/materials/agenda-114-cdni-01), makes use of cti,  In this case, the CWT issuer is distinct from the client that actually relays the token and is never in direct contact with the relying party (in this case a Content Delivery Network).  

There may be comparable cases such as delegated attestation, where the attester is not integrated with the entity but the entity must relay the token on behalf of the attester to the relying party.

**Comment by mcr** [comment]
Okay, let me ask the question differently: why are jti/cti mentioned at all?

**Comment by carl-wallace** [comment]
#308 removes this section, since cti/jti can be used without this section and there are not limitations on use a la those for iat.

**Comment by laurencelundblade** [comment]
Claims where removed
