### ISSUE TITLE
Add claims for public keys and similar

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#3]
(From David Wheeler)

What seems to be missing from the proposed structure is the ability to attach new key material into the EAT structure, with an attestation claim. The attestation claim can be that it was generated on the device, or generated inside the TEE and bound/sealed to the TEE. And perhaps even a purpose for the key material. A new attestation key, for example; or a special signing/authorization key for a particular application.
 
Many times, IMHO, it is useful to generate a new key that is attested in some way, and then future operations use that key. In fact, OTrP/TEEP has this implication, with the AIK keys for new installed Apps, but (IMO) it is not really that clearly spelled out, although I think the intention is clear.
 
Other attestation claims are also useful – the identity and cryptographic hash of the code of a particular TEE application; a DH public key to establish an encrypted channel; the set of root CA’s this TEE will trust; …

**Comment by mathias-arm** [comment]
It seems to me this effort is relevant to the issue: https://datatracker.ietf.org/doc/draft-ietf-ace-cwt-proof-of-possession/

**Comment by nedmsmith** [comment]
Attestation is different than proof of possession it is more like proof of protection or proof of integrity. In the TPM there is an added semantic that the key can only sign (attest to) data objects that are under the control of the TPM (TEE?). This avoids a possible confused deputy attack. If a key was not generated inside the trusted environment then it is possible the key could have been exposed to an attacker. This would make it less trustworthy as an attestation key because the key potentially could sign evidence that didn't pertain to the attester.

**Comment by laurencelundblade** [comment]
Addressed with PR #71
