### ISSUE TITLE
Should there be both "restricted" and "secure restricted" security levels

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#4]
See seclevel discussion in mail list archive: https://mailarchive.ietf.org/arch/browse/eat/

**Comment by nedmsmith** [comment]
The link to mailarchive doesn't appear to show messages related to this issue. Difficult to get context. My feedback related to levels is there isn't a clear use case or security model for the levels defined here. For example, the Bell-LaPadula security model defines security levels which are meaningful in that context. However, it isn't possible to map the levels defined in EAT because BL levels also have compartments and require a TCB boundary definition. These elements are not defined by EAT.

**Comment by laurencelundblade** [comment]
The right link to the previous discussion that seems worth reading.

https://mailarchive.ietf.org/arch/msg/eat/cCalQh6WIePUYgZr_amp6FfOHc4/

**Comment by laurencelundblade** [comment]
This claim is oriented around resistance to attack. There seems to be some consensus around that the discussion in the mail archive. This claim is also in line with other efforts like that in FIDO.

https://mailarchive.ietf.org/arch/msg/eat/cCalQh6WIePUYgZr_amp6FfOHc4/

Bell-LaPadula doesn't seem to be about resistance to attack and doesn't seem useful here.

**Comment by laurencelundblade** [comment]
The proposal for this open issue is to reduce to three security levels from four.

Alternatively we could go to five by adding a "system services" level that is roughly equivalent to root on Linux.

**Comment by laurencelundblade** [comment]
Fixed by #116
