### ISSUE TITLE
profile OIDs (and URIs) should be "absolute"

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#96]
```suggestion
A profile is identified by either an absolute URI {{!RFC3896}} or
an absolute OID (ASN.1 Type "OBJECT IDENTIFIER").
```

_Originally posted by @thomas-fossati in https://github.com/ietf-rats-wg/eat/pull/93#discussion_r584311652_

**Comment by thomas-fossati** [comment]
There are two reasons for this:
1. a philosophical one: we want the profile claim to not clash;
2. a technical one: by unwrapping the CBOR tag (i.e., `~oid`) the decoder looses the ability to distinguish between "absolute" OIDs and relative OIDs.  So, we need to explicitly say which type is legal.  Given point 1. above it's the absolute form that should be preferred.

**Comment by thomas-fossati** [comment]
> Given point 1. above it's the absolute form that should be preferred.

Note that this is not ideal since it removes the ability to express PENs in a succinct manner.

**Comment by laurencelundblade** [comment]
I think I prefer the absolute for simplicity and because it doesn't save that much.

Consider the PEN 50000.2 that might be used to indicate a profile. PEN assignments are up over 50,000 now. 

As an absolute OID this is 1.3.6.1.4.1.50000.2 and encodes in 11 bytes.

If we allow use of the relative PEN, then by not unwrapping then we get 3 bytes for the tag and 6 bytes for the RDN for a total of 9. We're saving 2 bytes for PENs.  But this adds 3 bytes for absolute OIDs.

It is always possible to go between a PEN and an absolute OID because the PEN prefix is well known. Are there any use cases where we need relative OIDs where the prefix is not well known? Maybe there is some OID prefix for the whole token from some context outside the token? Probably not I think. That would also be taking EAT further down the ASN.1 path where I hope not to go.

**Comment by thomas-fossati** [comment]
> If we allow use of the relative PEN, then by not unwrapping then we get 3 bytes for the tag and 6 bytes for the RDN for a total of 9. We're saving 2 bytes for PENs. But this adds 3 bytes for absolute OIDs.

I think it's two bytes for the tag not three, but that doesn't change the substance of your (very reasonable) conclusion.

> Are there any use cases where we need relative OIDs where the prefix is not well known? Maybe there is some OID prefix for the whole token from some context outside the token? Probably not I think.

I don't think so too.  Let's go with absolute then :-)

**Comment by laurencelundblade** [comment]
Fixed in https://github.com/ietf-rats-wg/eat/commit/41685066d17a580679e7bdb038d1a30042966920
